#!/usr/bin/python
#This cgi script is to generate tidal gauge pages

import os
import os.path
import re
import cgi
import cgitb
import sys
import subprocess
import urlparse
import urllib

#The following line is for debugging
#cgitb.enable(display=0, logdir="/tmp")
sys.stderr = sys.stdout
cgitb.enable()
MAPFILE_PATH = '/var/www/cgi-bin/maps/'
#cgitb.enable(logdir="/tmp/pytho.log")

maps = {'plainworld': MAPFILE_PATH + 'plainworld.map',
        'bathymetry': MAPFILE_PATH + 'bathymetry.map',
        'sst': MAPFILE_PATH + 'sst.map',
        'reynolds': MAPFILE_PATH + 'reynolds.map'}


def main():
    form = cgi.FieldStorage()
    if "map" in form:

#    print "Content-type: text/html\r\n\r\n";
#    print "<font size=+1>Environment</font><\br>";
#    for param in os.environ.keys():
#        print "<b>%20s</b>: %s<\br>" % (param,os.environ[param])
#    print os.environ["QUERY_STRING"]
#    print '\n'
        queryMap = urlparse.parse_qs(os.environ["QUERY_STRING"])
        queryMap["map"] = maps[form["map"].value]
        queryString = urllib.urlencode(queryMap, True)
#    print queryString
#    print urllib.unquote(queryString)
#    os.environ["QUERY_STRING"] = urllib.unquote(queryString)
        os.environ["QUERY_STRING"] = queryString
        subprocess.call(['/var/www/cgi-bin/mapserv'])
#    os.execl('/var/www/cgi-bin/mapserv')
#    subprocess.call(['/var/www/cgi-bin/mapserv', 'QUERY_STRING=' + urllib.unquote(queryString)])

main()

