#!/usr/bin/python
#This cgi script is to generate tidal gauge pages

import os
import os.path as path
import re
import cgi
import cgitb
import sys
import subprocess
import urlparse
import urllib
import string
import ocean.util.serverConfig as serverCfg

#The following line is for debugging
#cgitb.enable(display=0, logdir="/tmp")
sys.stderr = sys.stdout
cgitb.enable()
MAPFILE_PATH = '/var/www/cgi-bin/maps/'
#cgitb.enable(logdir="/tmp/pytho.log")

maps = {'plainworld': MAPFILE_PATH + 'plainworld.map',
        'bathymetry': MAPFILE_PATH + 'bathymetry.map',
        'sst': MAPFILE_PATH + 'sst.map',
        'reynolds': MAPFILE_PATH + 'reynolds.map'}
MAP_EAST_PATTERN = re.compile('east.png$')
MAP_WEST_PATTERN = re.compile('west.png$')

def main():
    form = cgi.FieldStorage()
 
    if "map" in form:
        queryMap = urlparse.parse_qs(os.environ["QUERY_STRING"])
        queryMap["map"] = maps[form["map"].value]
        
        if form["map"].value == 'reynolds':
            raster = form["raster"].value
            rasters = string.split(raster, " ")
            for file in rasters:
                url, filename = path.split(file)
                #copy file into the location that is specified in the map file
                #TODO
                #path = serverCfg.servers[serverCfg.currentServer]["mapImageDir"]
                #urllib.urlretrieve(file, path + filename)
                

                #detect the image file and add to the URL for the map variable substitution.
                if MAP_EAST_PATTERN.search(filename):
                    queryMap["eastFileName"] = filename
                elif MAP_WEST_PATTERN.search(filename):
                    queryMap["westFileName"] = filename

        queryString = urllib.urlencode(queryMap, True)
        os.environ["QUERY_STRING"] = queryString
        subprocess.call(['/var/www/cgi-bin/mapserv'])
main()

