#
#
#
#
#
#
regions = {"pi": ("pi",
                  {"llcrnrlat": -26,
                   "llcrnrlon": 134,
                   "urcrnrlat": 23,
                   "urcrnrlon": 214
                   },
                  "Pacific Islands"),
           "cook": ("pi",
                  {"llcrnrlat": -23,
                   "llcrnrlon": 193,
                   "urcrnrlat": -8,
                   "urcrnrlon": 203
                  },
                  "Cook Islands"),
           "fsm": ("pi", 
                  {"llcrnrlat": 5,
                   "llcrnrlon": 150,
                   "urcrnrlat": 11,
                   "urcrnrlon": 164
                  },
                  "Federated States of Micronesia"),
           "fiji": ("pi", 
                  {"llcrnrlat": -20,
                   "llcrnrlon": 176.5,
                   "urcrnrlat": -15,
                   "urcrnrlon": 183
                  },
                  "Fiji"),
           "kiribati": ("pi",
                  {"llcrnrlat": -12,
                   "llcrnrlon": 169,
                   "urcrnrlat": 5,
                   "urcrnrlon": 210
                  },
                  "Kiribati"),
           "marshall": ("pi",
                  {"llcrnrlat": 4,
                   "llcrnrlon": 160,
                   "urcrnrlat": 16,
                   "urcrnrlon": 173
                  },
                  "Marshall Islands"),
           "nauru": ("pi", 
                  {"llcrnrlat": -1,
                   "llcrnrlon": 166,
                   "urcrnrlat": 0,
                   "urcrnrlon": 168
                  },
                  "Nauru"),
           "niue": ("pi",
                  {"llcrnrlat": -20,
                   "llcrnrlon": 189,
                   "urcrnrlat": -18,
                   "urcrnrlon": 191
                  },
                  "Niue"),
           "palau": ("pi", 
                  {"llcrnrlat": 2,
                   "llcrnrlon": 131,
                   "urcrnrlat": 9,
                   "urcrnrlon": 135
                  },
                  "Palau"),
           "png": ("pi",
                  {"llcrnrlat": -12,
                   "llcrnrlon": 128,
                   "urcrnrlat": 1,
                   "urcrnrlon": 160
                  },
                  "Papua New Guinea"),
           "samoa": ("pi",
                  {"llcrnrlat": -15,
                   "llcrnrlon": 186.5,
                   "urcrnrlat": -12,
                   "urcrnrlon": 189
                  },
                  "Samoa"),
           "wsm_nor": ("pi",                     #Samoa Northern Coast. wsm is the ISO code of Samoa
                  {"llcrnrlat": -14,
                   "llcrnrlon": 186.5,
                   "urcrnrlat": -12,
                   "urcrnrlon": 189
                  },
                  "Samoa Northern Coast"),
           "wsm_sou": ("pi",                     #Samoa Southern Coast
                  {"llcrnrlat": -15,
                   "llcrnrlon": 186.5,
                   "urcrnrlat": -13.3,
                   "urcrnrlon": 189
                  },
                  "Samoa Southern Coast"),
           "solomon": ("pi", 
                  {"llcrnrlat": -12,
                   "llcrnrlon": 155,
                   "urcrnrlat": -4.8,
                   "urcrnrlon": 168
                  },
                  "Solomon Islands"),
           "tonga": ("pi", 
                  {"llcrnrlat": -22,
                   "llcrnrlon": 184,
                   "urcrnrlat": -15,
                   "urcrnrlon": 190
                  },
                  "Tonga"),
           "tuvalu": ("pi", 
                  {"llcrnrlat": -11,
                   "llcrnrlon": 177,
                   "urcrnrlat": -7,
                   "urcrnrlon": 180
                  },
                  "Tuvalu"),
           "vanuatu": ("pi",
                  {"llcrnrlat": -21,
                   "llcrnrlon": 166,
                   "urcrnrlat": -13,
                   "urcrnrlon": 170
                  },
                  "Vanuatu"),
           "aus": ("aus",
                  {"llcrnrlat": -50,
                   "llcrnrlon": 60,
                   "urcrnrlat": 20,
                   "urcrnrlon": 170
                  },
                  "Australia"),
           "glob": ("aus",
                  {"llcrnrlat": -90,
                   "llcrnrlon": 0,
                   "urcrnrlat": 90,
                   "urcrnrlon": 360
                  },
                  "Global Region"),
           "pac": ("aus",
                  {"llcrnrlat": -45,
                   "llcrnrlon": 100,
                   "urcrnrlat": 45,
                   "urcrnrlon": 300
                  },
                  "Pacific Ocean"),
           "ind": ("aus",
                  {"llcrnrlat": -45,
                   "llcrnrlon": 20,
                   "urcrnrlat": 45,
                   "urcrnrlon": 160
                  },
                  "Indian Ocean"),
           "ntr": ("aus",
                  {"llcrnrlat": -22,
                   "llcrnrlon": 94,
                   "urcrnrlat": 0,
                   "urcrnrlon": 174
                  },
                  "Northern Tropics"),
           "sth": ("aus",
                  {"llcrnrlat": -50,
                   "llcrnrlon": 94,
                   "urcrnrlat": -30,
                   "urcrnrlon": 174
                  },
                  "Southern Region"),
           "tas": ("aus",
                  {"llcrnrlat": -46,
                   "llcrnrlon": 150,
                   "urcrnrlat": -26,
                   "urcrnrlon": 174
                  },
                  "Tasman Sea"),
           "cor": ("aus",
                  {"llcrnrlat": -26,
                   "llcrnrlon": 142,
                   "urcrnrlat": -4,
                   "urcrnrlon": 174
                  },
                  "Coral Sea"),
           "nws": ("aus",
                  {"llcrnrlat": -22,
                   "llcrnrlon": 94,
                   "urcrnrlat": -4,
                   "urcrnrlon": 130
                  },
                  "North West Shelf"),
           "swr": ("aus",
                  {"llcrnrlat": -46,
                   "llcrnrlon": 94,
                   "urcrnrlat": -22,
                   "urcrnrlon": 116
                  },
                  "South West Region"),
           "eca": ("aus",
                  {"llcrnrlat": -50,
                   "llcrnrlon": 140,
                   "urcrnrlat": 0,
                   "urcrnrlon": 180
                  },
                  "East Australian Coast"),
           "wca": ("aus",
                  {"llcrnrlat": -50,
                   "llcrnrlon": 90,
                   "urcrnrlat": 0,
                   "urcrnrlon": 130
                  },
                  "West Australian Coast"),
           "sh": ("aus",
                  {"llcrnrlat": -90,
                   "llcrnrlon": 0,
                   "urcrnrlat": 0,
                   "urcrnrlon": 360
                  },
                  "Southern Hemisphere",
                  {"boundinglat": -10,
                   "lon0": 0
                  }),
           "sealevel": ("pi",
                       {"llcrnrlat": -50,
                        "llcrnrlon": 130,
                        "urcrnrlat": 10,
                        "urcrnrlon": 210,
                       },
                       "Pacific Sea Level")
                       }

