#!/usr/bin/env sh

# the number of days to keep files in the raster cache
KEEP_FOR_DAYS=7

CACHE_DIR=`python << EOF
import ocean.util

config = ocean.config.get_server_config()
print config['outputDir']
EOF`

if [ "x$CACHE_DIR" = "x" ]; then
    echo "CACHE_DIR EMPTY, BAD"
    exit 1
fi

find $CACHE_DIR -type f -mtime +$KEEP_FOR_DAYS -exec rm -f '{}' \;
