#!/usr/bin/python
#
# (c) 2012 Commonwealth of Australia
#     Australian Bureau of Meteorology, COSPPac COMP
#     All Rights Reserved
#
# Authors: Danielle Madeley <d.madeley@bom.gov.au>
#          Sheng Guo <s.guo@bom.gov.au>

import os
import os.path
import re
import subprocess
import urlparse
import urllib

import ocean.util as util

def main():
    config = util.get_server_config()

    queryMap = urlparse.parse_qs(os.environ["QUERY_STRING"])

    if 'map' in queryMap:
        map = queryMap['map'][0]
        queryMap['map'] = util.get_resource('maps', map + '.map')

        if map == 'raster':
            rasters = queryMap['raster'][0].split(' ')

            MAP_EAST_PATTERN = re.compile('east.png$')
            MAP_WEST_PATTERN = re.compile('west.png$')

            for file in rasters:
                filename = os.path.basename(file)

                if MAP_EAST_PATTERN.search(filename):
                    queryMap['eastFileName'] = os.path.join(config['outputDir'],
                                                            filename)
                elif MAP_WEST_PATTERN.search(filename):
                    queryMap['westFileName'] = os.path.join(config['outputDir'],
                                                            filename)

    queryString = urllib.urlencode(queryMap, True)
    os.environ['QUERY_STRING'] = queryString
    subprocess.call(config['mapservPath'])

if __name__ == '__main__':
    main()
