#!/usr/bin/python
#This cgi script is to generate tidal gauge pages

import os
import os.path
import re
import cgi
import cgitb
import sys
import subprocess
import urlparse
import urllib
import string

import ocean.util as util

#The following line is for debugging
#cgitb.enable(display=0, logdir="/tmp")
sys.stderr = sys.stdout
cgitb.enable()
#cgitb.enable(logdir="/tmp/pytho.log")

MAP_EAST_PATTERN = re.compile('east.png$')
MAP_WEST_PATTERN = re.compile('west.png$')

def main():
    form = cgi.FieldStorage()

    if "map" in form:
        queryMap = urlparse.parse_qs(os.environ["QUERY_STRING"])
        queryMap['map'] = util.get_resource('maps', form['map'].value + '.map')

        if form['map'].value in [ 'reynolds', 'sealevel' ]:
            raster = form["raster"].value
            rasters = string.split(raster, " ")
            for file in rasters:
                url, filename = os.path.split(file)
                #copy file into the location that is specified in the map file
                #TODO
                #path = serverCfg.servers[serverCfg.currentServer]["mapImageDir"]
                #urllib.urlretrieve(file, path + filename)

                #detect the image file and add to the URL for the map variable substitution.
                if MAP_EAST_PATTERN.search(filename):
                    queryMap["eastFileName"] = filename
                elif MAP_WEST_PATTERN.search(filename):
                    queryMap["westFileName"] = filename

        queryString = urllib.urlencode(queryMap, True)
        os.environ["QUERY_STRING"] = queryString
        subprocess.call(util.get_server_config()['mapservPath'])

main()

